### ISSUE TITLE
[bug] "Application is duplicated" when environment search path contains trailing slash

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#101]
```
myks render envs/mykso/dev/
```

Results in

```
2:38PM ERR [mykso-dev > init] Duplicated application app_name=argocd
2:38PM ERR [mykso-dev > init] Duplicated application app_name=httpbingo-1
2:38PM ERR [mykso-dev > init] Duplicated application app_name=httpbingo-2
```

despite:

```yaml
#@data/values
---
environment:
  id: mykso-dev
  applications:
    - proto: argocd
    - proto: httpbingo
      name: httpbingo-1
    - proto: httpbingo
      name: httpbingo-2
```
