### ISSUE TITLE
[bug] myks mandates a vendir.yaml structure whereby the entire path is held at directory level

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#171]
Composite paths such as this lead to an empty vendor directory:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: "charts/"
    contents:
      - path: #@ app.chart.name
        helmChart:
          name: #@ app.chart.name
          version: #@ app.chart.version
          repository:
            url: #@ app.chart.url
```
