### ISSUE TITLE
[bug] directory source in vendir config is broken

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#189]
For example, the following vendir config can't be used with myks:

```yaml
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: ytt
    contents:
      - path: local-app
        directory:
          path: vendor/app
```
