### ISSUE TITLE
[feature] Support for local helm charts

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#194]
While using ytt is great, it is not as well known as helm and in some cases sticking to helm reduces complexity and makes it easier to introduce myks. Therefore, we could introduce a new folder type in prototypes that contains local charts, e.g.:

```
prototypes:
  my-app:
    helm
    vendir
    ytt
    **chart**
```

The chart folder would contain a local helm chart in the standard format:

```
chart:
  templates
  Chart.yaml
  Chart.lock
  values.yaml
```

When rendering, the local charts would be templated and added to the remote chart (if there is one).

**Comment by Zebradil** [comment]
What about having local charts in a shared space? The example can be placed in `repo/charts/my-app` in the repository root (`repo` probably should be named differently).

With the following vendir config (when #191 gets merged):

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/my-app
  contents:
  - path: .
    directory:
      path: repo/charts/my-app
```

I believe that complex prototypes should reside outside of the myks configuration tree. They should probably have their own life cycle. They will be also more reusable when they reside outside of myks' prototypes directory — they can be even used on their own! :-)
