### ISSUE TITLE
[feat] Implement per-chart configuration

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#261]
Currently, the schema of myks' helm configuration looks like this:

```yaml
helm:
  #! If defined, passed as `--api-version` for `helm-template`.
  capabilities:
    - "" #! e.g. "monitoring.coreos.com/v1"
  #! If true, adds `--include-crds` flag to `helm template`.
  includeCRDs: true
  #! If defined, passed as a value of `--kube-version` for `helm template`.
  kubeVersion: ""
  #! If defined, passed as a value of `--namespace` for `helm template`.
  namespace: ""
  #! If true, run "helm dependency build" before rendering. This is required for helm charts with dependencies that are pulled from git repositories.
  buildDependencies: false

```

These configuration values are applied to all helm charts used by an application. Being able to select different per-chart values for `namespace`, `includeCRDs` and other not yet present options can be beneficial.

The proposal is to add `helm.charts` key with a map of per-chart configurations (leaving the rest as it is):

```yaml
helm:
  ...
  #! Per-chart configuration. The key is the name of the chart in the charts directory.
  #! Values override the global configuration.
  charts:
    httpbingo:
      includeCRDs: false
      namespace: bingo
```
