### ISSUE TITLE
myks fails to render githubRelease

### ISSUE THREAD

**Issue by johannesploetner** [mykso/myks#469]
Hi,

I would expect the following base.yaml to render:

```yaml
#@ load("@ytt:data", "data")

#@ app = data.values.application
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: rabbitmq-cluster-operator
    contents:
      - path: .
        githubRelease:
          slug: rabbitmq/cluster-operator
          tag: v2.12.1
          disableAutoChecksumValidation: true
          assetNames: ["cluster-operator.yml"]
        includePaths:
        - cluster-operator.yml
```

`myks sync` seems to fetch the required asset correctly. `myks render` however complains about `Empty ytt output`. The expected behavior would be to have the resources rendered correctly.

**Comment by Zebradil** [comment]
Hi, thank you for filing the issue!

For sources to be rendered, myks expects them to be found in particular places:

- `charts/<chart name>/` for helm charts
- `ytt/` for raw YAML and YTT templates
- `static/` for static files

This vendir configuration should work:

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: ytt/rabbitmq-cluster-operator
    contents:
      - path: .
        githubRelease:
          slug: rabbitmq/cluster-operator
          tag: v2.12.1
          disableAutoChecksumValidation: true
          assetNames: ["cluster-operator.yml"]
        includePaths:
          - cluster-operator.yml
```
