### ISSUE TITLE
Cleanup old vendir directories

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#61]
When a vendir directory is removed from a vendir.yaml, it is not cleaned up in the vendor directory. For example, if there are two directories:

```yaml
directories:
  - path: charts/hello
    contents:
      - path: .
        helmChart:
          # ...
  - path: ytt
    contents:
      - path: raw-hello
        git:
          # ...
```

`vendor/charts` and `vendor/ytt` are created.

When one of the directories is removed from the config:

```yaml
directories:
  - path: charts/hello
    contents:
      - path: .
        helmChart:
          # ...
```

Both `vendor/charts` and `vendor/ytt` stay and impact the rendering step.

It doesn't look like a vendir bug, so I suggest including a cleanup step. The logic for that will be to check if there are `vendor/*` subdirectories that are not controlled by vendir and remove them.
