### ISSUE TITLE
[bug] vendir config with multiple paths is not supported

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#81]
Trying to `myks sync` with the following vendir config:

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt
  contents:
  - path: keycloak-operator
    git:
      url: https://github.com/keycloak/keycloak-k8s-resources
      ref: 22.0.1
    includePaths:
    - kubernetes/keycloaks.k8s.keycloak.org-v1.yml
    - kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
    - kubernetes/kubernetes.yml
    newRootPath: kubernetes
  - path: keycloak-realm-operator
    git:
      url: https://github.com/keycloak/keycloak-realm-operator
      ref: 1.0.0
    includePaths:
    - deploy/crds/legacy.k8s.keycloak.org_externalkeycloaks_crd.yaml
    - deploy/crds/legacy.k8s.keycloak.org_keycloakclients_crd.yaml
    - deploy/crds/legacy.k8s.keycloak.org_keycloakrealms_crd.yaml
    - deploy/crds/legacy.k8s.keycloak.org_keycloakusers_crd.yaml
    - deploy/role.yaml
    - deploy/role_binding.yaml
    - deploy/service_account.yaml
    - deploy/operator.yaml
    newRootPath: deploy
  - path: keycloak-operator-crs
    git:
      url: https://github.com/keycloak/keycloak-realm-operator
      ref: 1.0.0
    includePaths:
    - deploy/examples/example-kc-deployment.yaml
    - deploy/examples/external-keycloak.yaml
    - deploy/examples/realm-new/example-realm.yaml
    - deploy/examples/realm-new/external-realm.yaml
    - deploy/examples/example-client.yaml
    - deploy/examples/example-user.yaml
    newRootPath: deploy
```

leads to the error:

> FTL Unable to sync vendir configs error="Vendir config contains more than one contents for path: ytt. This is not supported"
